sudo: true
language: go
go: 1.8.x
before_install:
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
- source ~/.bashrc
- nvm install stable
- npm install -g yarn
- yarn install --pure-lockfile
- npm install -g grunt-cli
script:
- mv $GOPATH/src/github.com/lichao-mobanche $GOPATH/src/github.com/grafana
- make
after_script:
- apt-get install gnu-tar
- apt-get install rpm
- gem install fpm
- go run build.go package
deploy:
  provider: releases
  api_key:
    secure: ehXWwheIegX09r9NZagbgJQV6YV1+ofxM5SEzKhAAyR3KhP+ww1nc9NwHU2fhcJWR8CDAXgIyfhCq+eyvqrUxX1ezm7n2/DZu5JcASty7Xcz3vXS2VsLdaw0N+ZUeZB94pdJr5dC/GfCL20FxGCjacIRc2DUSH5sAeBULt5yMaWzmL3c/q74ZalS1jXRAlykbe9MWEgrO11w+Pg6b3knsy6gGNV8/9qbtER62cMOp0PLBawQhH4qNcrnqVW30jlu9jKX0b9WtRP/SsDvsJG2piO3YRctaSjalOB9U93P9ArRa+rTmKitOTFhlL8mUBA3xd3pk+AKVQRGEwGgBezLx++vQb8qKpnUamI8CDWsSf+Bftht9n3ZG5X3nn508bz66/8BEXKFEAeH0PoLJ0fLBOdytSI3GteZNZlkwqs3KzUeVk/TDhTKHBog3AIm8kRuBFCXdiLrSPMFvBgmxrz3x8iYK+Og/rKUEKj9QCSigCGUJspsHINe4AmOKOUaDA32T8U5VMc9lq/87oHglj0aqyAOvh6siDGlxAjxNzpo4O5KbUci2Yjms09iPPCAy7KDCCGeJ0L2Jyptf6zL1N9pUdy8wu9ZkISbAtaeZNhHaEDPVqKUCXUOYPwaLanRfjdGecyqDRZ8txaAh2lOHgnjyqIA2qfsk9zBvVZvHbfOgks=
  file: 
  - dist/grafana-4.4.3-1.x86_64.rpm
  - dist/grafana_4.4.3_amd64.deb
  on:
    tags: true
