sudo: true
language: go
go: 1.8.x
before_install:
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash
- source ~/.bashrc
- nvm install stable
- npm install -g yarn
- yarn install --pure-lockfile
- npm install -g grunt-cli
script:
- mv $GOPATH/src/github.com/lichao-mobanche $GOPATH/src/github.com/grafana
- make
after_script:
- apt-get install gnu-tar
- apt-get install rpm
- gem install fpm
- go run build.go package
deploy:
  provider: releases
  skip_cleanup: true
  file:
  - dist/grafana-4.4.3-1.x86_64.rpm
  - dist/grafana_4.4.3_amd64.deb
  password:
    secure: O8S/bPHre975R2h16JZUn3boNgTYzvPntnAP6Kp6D+dBi6ekXGBzql2cCVkAwWP0pqah++x9PaZ7WHQ9ouewJ2Cis9rhPQ5LWdGP0u9I/pGcRoMzIWji/9Qn6RqAun39pDQgmZmUPyOT3PmkwJN+dBFfB/V1NGQCpn33TVK1YPkDPxUxaKhsbyLSj/vLGs66vw8zcJa985lw5S3JXZLQA7gm79h8bWDpwQopxRnabMXesSnI4N55/A/r2HqlCGXzwbEanbF1IUCxADvp9KZ4P8cdb8UNyuHRWIWe8MnpD4SHWXaRHTzJduM7DL6fYCSK039Zy5jboYn80Sc95QLlyHYMGZuTu3kQccJd8F04RTzYQUcXgxpbNhClhujf7b2SVGbRmLu7qHc0GCqOk02YTR9b1J4RTE9DgYBjjd+R/cguPBkW9mpmV02f69dvnoeAKnlyhDLmpjnxf3OJphkAT0908U+bVVhKIR13yJw35FNxRnymt5F4SZEeB9TvWbHJC566jhmEsVpR7whLe+81SUO+ssrllpS1N26cOS+TonWZIeCvtmSs6XaGd/0jX2k34IcmY3pRhU0RIlWP/044qqMtREH7VCWpYRwHyOR8dgd8GRtBbyRFJ5IddTYUqOOt7zQVzhmVcekjuyPgT6/L39eAHGm+CMvFTjp0u86Lv4E=
on:
    tags: true
    repo: lichao-mobanche/grafana
    branches:  # ← new!